import { styled } from '@kuma-ui/core';
import { Inter } from 'next/font/google';
import { Header } from '~/components/Header';
import { Footer } from '~/components/Footer';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Main = styled('main')`
  max-width: 768px;
  width: 100%;
  margin: auto;
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
